nelmio_api_doc:
    documentation:
        info:
            title: 'Orders API'
            description: 'API documentation for managing orders'
            version: 1.0.0
    areas: # to filter documented areas
        default:
            path_patterns: ['^/orders']